### ISSUE TITLE
Background color not exported in png

### ISSUE THREAD

**Issue by thomaskelder** [idekerlab/cyREST#22]
The method http://example.com/v1/networks/networkId/views/first.png does not seem to include the background color of the network. The following is an export using that function from a network with a red background:

![network](https://cloud.githubusercontent.com/assets/1672609/7932177/89a65c18-0916-11e5-97f1-179d7d237c08.png)

This is how it looks like in Cytoscape:

![screenshot from 2015-06-02 11 00 46](https://cloud.githubusercontent.com/assets/1672609/7932188/a538c59c-0916-11e5-97d9-a5d383d4eb3a.png)

If I export the network using Cytoscape directy (so not through REST), it renders correctly:

![network2](https://cloud.githubusercontent.com/assets/1672609/7932202/c5ff8fa4-0916-11e5-9bcf-749d325ba6e0.png)

**Comment by keiono** [comment]
Fixed in 1.1.0.
