### ISSUE TITLE
getting cyRest up and running

### ISSUE THREAD

**Issue by jooolia** [idekerlab/cyREST#25]
Hi,

I'm looking to use cyRest with R (and potentially with python), but am having trouble getting past the installation. From the wiki page: https://github.com/idekerlab/cyREST/wiki/Installation-Guide I get to the section "Test your installation", but am not able to get any status message. I have even tried changing the port number via Cytoscape. Any ideas on how to troubleshoot? Thanks!

Specs:
Cytoscape 3.2.1
cyREST 1.1.0
java version 1.7.0_71
running Linux Fedora 19

**Comment by keiono** [comment]
Hi.

You need to install latest version of Java 8 to run this application, and make sure your $JAVA_HOME is set to the Java 8 home directory.

 If you still have problems, please let me know.

**Comment by jooolia** [comment]
Excellent! Java 8 did it! Thanks!
