### ISSUE TITLE
using other Cytoscape apps with cyRest?

### ISSUE THREAD

**Issue by jooolia** [idekerlab/cyREST#26]
Hi, is there documentation on using other Cytoscape apps with cyRest? For example I have [Moduland 2.0](http://apps.cytoscape.org/apps/moduland20) installed and would like to call it from R using cyRest. I thought I could call it a bit like the layout (because I can easily access custom installed layouts here): 
```
layout.params.url = paste(base.url, "apply/layouts/allegro-spring-electric/parameters", sep="/")
PUT(layout.params.url, body=toJSON(list(layout.params)), encode = "json")

apply.layout.url = paste(base.url, "apply/layouts/allegro-spring-electric", toString(network.suid), sep="/")
GET(apply.layout.url)
```
However I can't figure out what to use for other apps here instead of "layouts". Is this even possible? 

Thanks! Julia

**Comment by keiono** [comment]
Current version of cyREST only supports functions using core API.  For example, you can access all layouts including 3rd party ones from cyREST:  

```
http://localhost:1234/v1/apply/layouts
```

```json
[
"attribute-circle",
"allegro-weak-clustering",
"allegro-edge-repulsive-fruchterman-reingold",
"stacked-node-layout",
"allegro-edge-repulsive-strong-clustering",
"allegro-strong-clustering",
"degree-circle",
"allegro-fruchterman-reingold",
"allegro-edge-repulsive-spring-electric",
"circular",
"attributes-layout",
"kamada-kawai",
"force-directed",
"allegro-edge-repulsive-weak-clustering",
"grid",
"hierarchical",
"allegro-spring-electric",
"fruchterman-rheingold",
"isom"
]
```

But this is true only for core APIs.  Even if an App has it's own public API, cyREST cannot access it.  This is a known issue and planed to support in future versions.

**Comment by jooolia** [comment]
Ok thanks for the explanation.
