### ISSUE TITLE
Unable to resolve 113.0: missing requirement [113.0] osgi.ee

### ISSUE THREAD

**Issue by frederickayala** [idekerlab/cyREST#28]
Hi,

I am getting the following error when Cytoscape is starting cyREST:

- 2015-08-05 23:29:41,424 [fileinstall-/Users/myuser/CytoscapeConfiguration/3/apps/installed] WARN  org.apache.felix.fileinstall - Error while starting bundle: file:/Users/myuser/CytoscapeConfiguration/3/apps/installed/cyREST-v1.1.1.jar
org.osgi.framework.BundleException: Unresolved constraint in bundle org.cytoscape.rest.cy-rest [113]: Unable to resolve 113.0: missing requirement [113.0] osgi.ee; (&(osgi.ee=JavaSE)(version=1.8))

My Java SE version is:
- java version "1.8.0_51"
- Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
- Java HotSpot(TM) 64-Bit Server VM (build 25.51-b03, mixed mode)

I am running it on a Mac OS X Yosemite Version 10.10.4

Any suggestion on how to fix this?

Thanks!

**Comment by keiono** [comment]
Does your Cytoscape instance actually uses Java 8?  Could you double check this message?

http://chianti.ucsd.edu/~kono/images/cyrest_java.png

Also, is your Cytoscape version is 3.2.1?

**Comment by frederickayala** [comment]
Indeed, the problem was that my Cytoscape version was 3.2.0. I upgraded to 3.2.1 and it worked perfectly!

Thanks again! ^_^
